import { Router } from 'express';
import { authenticate } from '../middleware/auth';
import { rbac } from '../middleware/rbac';
import { validate } from '../middleware/validate';
import { TurmaController, criarTurmaSchema, atualizarTurmaSchema, idParam, matriculaParam, matricularSchema } from '../controllers/TurmaController';
import { DisciplinaController, turmaIdParam } from '../controllers/DisciplinaController';
import { ImportacaoController, importarSchema } from '../controllers/ImportacaoController';

const router = Router();
router.use(authenticate);
router.get('/', rbac('A', 'P'), TurmaController.listar);
router.get('/:id', rbac('A', 'P'), validate(idParam, 'params'), TurmaController.buscar);
router.get('/:turmaId/disciplinas', rbac('A', 'P'), validate(turmaIdParam, 'params'), DisciplinaController.listarPorTurma);
router.post('/', rbac('A'), validate(criarTurmaSchema), TurmaController.criar);
router.put('/:id', rbac('A'), validate(idParam, 'params'), validate(atualizarTurmaSchema), TurmaController.atualizar);
router.delete('/:id', rbac('A'), validate(idParam, 'params'), TurmaController.excluir);
router.post('/:id/matriculas', rbac('A'), validate(idParam, 'params'), validate(matricularSchema), TurmaController.matricular);
router.delete('/:id/matriculas/:alunoId', rbac('A'), validate(matriculaParam, 'params'), TurmaController.desmatricular);
router.post('/importar-alunos', rbac('A'), validate(importarSchema), ImportacaoController.importarAlunos);
export default router;
